Repository ndlamdev/fashion-e-commerce-back-end-sping-boot, pull requests merged in 2025-04, with the labels that each got.

#14 feat: Hoàn thành khởi tạo dự án và cấu hình
  profile_service/.gitattributes
  profile_service/.gitignore
  profile_service/build.gradle
  profile_service/gradlew
  profile_service/gradlew.bat
  profile_service/settings.gradle
  profile_service/src/main/java/com/lamnguyen/profile_service/ProfileServiceApplication.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/CorsConfigurationSourceImpl.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/DataInitializer.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/FlywayConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/JwtConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/MvcConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/RedisConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/ResponseMessageConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/SecurityConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/converter/JwtAuthenticationConverterImpl.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/converter/StringToObjectHttpMessageConverter.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/endpoint/CustomAuthenticationEntryPoint.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/exception/ApplicationException.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/exception/ExceptionEnum.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/exception/GlobalException.java
  profile_service/src/main/java/com/lamnguyen/profile_service/controller/Greeting.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/ApiResponse.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/ApiResponseError.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/ApiResponseSuccess.java
  profile_service/src/main/java/com/lamnguyen/profile_service/message/SaveUserDetailMessage.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/JWTPayload.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/SimplePayload.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/annotation/ApiMessageResponse.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/enums/JwtType.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/enums/SexEnum.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/property/ApplicationProperty.java
  profile_service/src/main/resources/application.yaml
  profile_service/src/test/java/com/lamnguyen/profile_service/ProfileServiceApplicationTests.java
Labels: enhancement, good first issue

#15 feat: Hoàn thành khởi tạo dự án django và train thử mô hình
  .gitignore
  profile_service/HELP.md
  search_by_image_using_ai_service/manage.py
  search_by_image_using_ai_service/search_app/__init__.py
  search_by_image_using_ai_service/search_app/admin.py
  search_by_image_using_ai_service/search_app/apps.py
  search_by_image_using_ai_service/search_app/migrations/__init__.py
  search_by_image_using_ai_service/search_app/models.py
  search_by_image_using_ai_service/search_app/service/__init__.py
  search_by_image_using_ai_service/search_app/service/query_similar.py
  search_by_image_using_ai_service/search_app/service/train_and_save.py
  search_by_image_using_ai_service/search_app/tests.py
  search_by_image_using_ai_service/search_app/urls.py
  search_by_image_using_ai_service/search_app/views.py
  search_by_image_using_ai_service/search_by_image_using_ai_service/__init__.py
  search_by_image_using_ai_service/search_by_image_using_ai_service/asgi.py
  search_by_image_using_ai_service/search_by_image_using_ai_service/settings.py
  search_by_image_using_ai_service/search_by_image_using_ai_service/urls.py
  search_by_image_using_ai_service/search_by_image_using_ai_service/wsgi.py
Labels: enhancement, good first issue, wontfix

#16 feat: Hoàn thành cấu hình dự án product service
  product_service/.gitattributes
  product_service/.gitignore
  product_service/build.gradle
  product_service/gradlew
  product_service/gradlew.bat
  product_service/settings.gradle
  product_service/src/main/java/com/lamnguyen/product_service/MvcConfig.java
  product_service/src/main/java/com/lamnguyen/product_service/ProductServiceApplication.java
  product_service/src/main/java/com/lamnguyen/product_service/config/CorsConfigurationSourceImpl.java
  product_service/src/main/java/com/lamnguyen/product_service/config/JwtConfig.java
  product_service/src/main/java/com/lamnguyen/product_service/config/RedisConfig.java
  product_service/src/main/java/com/lamnguyen/product_service/config/ResponseMessageConfig.java
  product_service/src/main/java/com/lamnguyen/product_service/config/SecurityConfig.java
  product_service/src/main/java/com/lamnguyen/product_service/config/converter/JwtAuthenticationConverterImpl.java
  product_service/src/main/java/com/lamnguyen/product_service/config/converter/StringToObjectHttpMessageConverter.java
  product_service/src/main/java/com/lamnguyen/product_service/config/endpoint/CustomAuthenticationEntryPoint.java
  product_service/src/main/java/com/lamnguyen/product_service/config/exception/ApplicationException.java
  product_service/src/main/java/com/lamnguyen/product_service/config/exception/ExceptionEnum.java
  product_service/src/main/java/com/lamnguyen/product_service/config/exception/GlobalException.java
  product_service/src/main/java/com/lamnguyen/product_service/controller/GreetingController.java
  product_service/src/main/java/com/lamnguyen/product_service/domain/ApiResponse.java
  product_service/src/main/java/com/lamnguyen/product_service/domain/ApiResponseError.java
  product_service/src/main/java/com/lamnguyen/product_service/domain/ApiResponseSuccess.java
  product_service/src/main/java/com/lamnguyen/product_service/model/CollectionPricingPolicy.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Condition.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Image.java
  product_service/src/main/java/com/lamnguyen/product_service/model/JWTPayload.java
  product_service/src/main/java/com/lamnguyen/product_service/model/MongoBaseEntity.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Option.java
  product_service/src/main/java/com/lamnguyen/product_service/model/OptionItem.java
  product_service/src/main/java/com/lamnguyen/product_service/model/OptionsValue.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Product.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Review.java
  product_service/src/main/java/com/lamnguyen/product_service/model/SimplePayload.java
  product_service/src/main/java/com/lamnguyen/product_service/model/SyncProduct.java
  product_service/src/main/java/com/lamnguyen/product_service/model/Variant.java
  product_service/src/main/java/com/lamnguyen/product_service/repository/IProductRepository.java
  product_service/src/main/java/com/lamnguyen/product_service/utils/annotation/ApiMessageResponse.java
  product_service/src/main/java/com/lamnguyen/product_service/utils/enums/JwtType.java
  product_service/src/main/java/com/lamnguyen/product_service/utils/enums/OptionType.java
  product_service/src/main/java/com/lamnguyen/product_service/utils/format/folder/FormatFolder.java
  product_service/src/main/java/com/lamnguyen/product_service/utils/property/ApplicationProperty.java
  product_service/src/main/resources/application.yaml
Labels: enhancement, good first issue

#24 finish base CRUD profile service
  .gitignore
  authentication_service/src/main/java/com/lamnguyen/authentication_service/controller/AuthenticationController.java
  authentication_service/src/main/resources/application.yaml
  config_server/gradlew
  docker-compose.yml
  eureka_service/src/main/resources/application.yaml
  profile_service/Dockerfile
  profile_service/build.gradle
  profile_service/cli/dump_database.sh
  profile_service/cli/start_docker_compose.sh
  profile_service/cli/start_project.sh
  profile_service/docker-compose.yml
  profile_service/src/main/java/com/lamnguyen/profile_service/config/SecurityConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/auditing/AuditorAwareImpl.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/auditing/PersistentConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/exception/ExceptionEnum.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/kafka/InfoAddressShippingTopicConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/config/kafka/RestTemplateConfig.java
  profile_service/src/main/java/com/lamnguyen/profile_service/controller/AddressController.java
  profile_service/src/main/java/com/lamnguyen/profile_service/controller/AdminAddressController.java
  profile_service/src/main/java/com/lamnguyen/profile_service/controller/CustomerController.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/ApiPaging.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/dto/AddressDto.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/dto/CustomerDto.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/request/SaveAddressRequest.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/request/SaveCustomerRequest.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/response/AddressResponse.java
  profile_service/src/main/java/com/lamnguyen/profile_service/domain/response/SaveCustomerResponse.java
  profile_service/src/main/java/com/lamnguyen/profile_service/mapper/IAddressMapper.java
  profile_service/src/main/java/com/lamnguyen/profile_service/mapper/ICustomerMapper.java
  profile_service/src/main/java/com/lamnguyen/profile_service/message/InfoAddressShipping.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/SimplePayload.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/entity/Address.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/entity/BaseEntity.java
  profile_service/src/main/java/com/lamnguyen/profile_service/model/entity/Customer.java
  profile_service/src/main/java/com/lamnguyen/profile_service/repository/IAddressRepository.java
  profile_service/src/main/java/com/lamnguyen/profile_service/repository/ICustomerRepository.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/IAddressService.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/ICustomerService.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/consumer/CustomerConsumer.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/producer/CustomerProducer.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/v1/AddressServiceImpl.java
  profile_service/src/main/java/com/lamnguyen/profile_service/service/v1/CustomerServiceImpl.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/JwtTokenUtil.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/annotation/ValidInternationalPhone.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/validation/InternationalPhoneValidator.java
  profile_service/src/main/java/com/lamnguyen/profile_service/utils/validation/MyPhoneNumberUtil.java
  profile_service/src/main/resources/application.yaml
  profile_service/src/main/resources/db/migration/V1__create_database.sql
  profile_service/src/main/resources/db/migration/V2__init_data.sql
Labels: enhancement
